source_dir = "/Users/philipesclamado/Downloads"
dest_dir_sfx = "/Users/philipesclamado/Downloads/SFX"
dest_dir_music = "/Users/philipesclamado/Downloads/Music"
dest_dir_video = "/Users/philipesclamado/Downloads/Video"
dest_dir_image = "/Users/philipesclamado/Downloads/Image"
dest_dir_documents = "/Users/philipesclamado/Downloads/Documents"